"""Test data: 10 realistic opportunities with known values."""

TEST_OPPORTUNITIES = [
    {
        "project_client": "IndTrade Export Solutions",
        "platform": "LinkedIn Jobs",
        "requirement": "Research feasibility of exporting to 3 new markets in Southeast Asia. Analyze tariffs, customer segments, local competitors, and prepare executive summary.",
        "payment": 45000,
        "estimated_days": 7,
        "deadline": "Within 10 days",
        "application_url": "https://www.linkedin.com/jobs/view/example1",
        "source_url": "https://www.linkedin.com/jobs",
        "posted_date": "2024-10-01",
        "currency": "INR",
        "status": "NEW",
        "why_fit": "Perfect match: market research, feasibility analysis, competitor mapping, customer segmentation.",
    },
    {
        "project_client": "EventsNorth India",
        "platform": "Upwork",
        "requirement": "Create sponsorship strategy and prospecting list for a 3-city event. Identify suitable brands, draft sponsorship tiers, prepare outreach plan.",
        "payment": 32000,
        "estimated_days": 5,
        "deadline": "Immediate",
        "application_url": "https://www.upwork.com/jobs/example2",
        "source_url": "https://www.upwork.com",
        "posted_date": "2024-10-02",
        "currency": "INR",
        "status": "NEW",
        "why_fit": "Strong fit: sponsorship/business development, market intelligence, commercial planning.",
    },
    {
        "project_client": "StartupHub Venture",
        "platform": "Fiverr",
        "requirement": "Validate business model for a fintech startup. Assess market size, customer personas, competitor landscape, pricing strategy. Deliver business model canvas.",
        "payment": 28000,
        "estimated_days": 6,
        "deadline": "2 weeks",
        "application_url": "https://www.fiverr.com/gigs/example3",
        "source_url": "https://www.fiverr.com",
        "posted_date": "2024-09-30",
        "currency": "INR",
        "status": "NEW",
        "why_fit": "Excellent match: business model design, customer discovery, market analysis, competitor research.",
    },
    {
        "project_client": "Local Manufacturing Group",
        "platform": "Workana",
        "requirement": "Create vendor database and comparison for 5 suppliers across packaging, logistics, and quality services in North India. Include pricing, terms, capability matrix.",
        "payment": 22000,
        "estimated_days": 4,
        "deadline": "7 days",
        "application_url": "https://www.workana.com/jobs/example4",
        "source_url": "https://www.workana.com",
        "posted_date": "2024-10-03",
        "currency": "INR",
        "status": "NEW",
        "why_fit": "Strong fit: vendor research, operations planning, commercial evaluation, SOP development.",
    },
    {
        "project_client": "Education NGO India",
        "platform": "CSR/NGO Portal",
        "requirement": "Research and map 20 potential CSR partner organizations in education sector. Create prospect list with funding status, program focus, contact details, and partnership fit assessment.",
        "payment": 38000,
        "estimated_days": 8,
        "deadline": "Within 2 weeks",
        "application_url": "https://www.ngosinindia.org/opportunities/example5",
        "source_url": "https://www.ngosinindia.org",
        "posted_date": "2024-10-01",
        "currency": "INR",
        "status": "NEW",
        "why_fit": "Good fit: opportunity mapping, stakeholder research, market intelligence, commercial strategy.",
    },
    {
        "project_client": "RetailChain Expansion",
        "platform": "PeoplePerHour",
        "requirement": "Territory analysis for 5 potential retail locations. Research customer demographics, competitor presence, foot traffic potential, rental rates, regulatory requirements.",
        "payment": 35000,
        "estimated_days": 7,
        "deadline": "10 days",
        "application_url": "https://www.peopleperhour.com/jobs/example6",
        "source_url": "https://www.peopleperhour.com",
        "posted_date": "2024-10-02",
        "currency": "INR",
        "status": "NEW",
        "why_fit": "Perfect match: territory research, market analysis, competitor mapping, feasibility analysis.",
    },
    {
        "project_client": "Consulting Firm ABC",
        "platform": "LinkedIn (Consulting)",
        "requirement": "Market opportunity analysis for healthcare services in 3 metros. Document market size, growth trends, regulatory landscape, competitive positioning, entry strategy.",
        "payment": None,  # UNKNOWN
        "estimated_days": 10,
        "deadline": "3 weeks",
        "application_url": "https://www.linkedin.com/jobs/view/example7",
        "source_url": "https://www.linkedin.com/jobs",
        "posted_date": "2024-09-29",
        "currency": "INR",
        "status": "NEW",
        "why_fit": "Good fit for skills, but payment unknown - confidence will be lower.",
    },
    {
        "project_client": "B2B SaaS Company",
        "platform": "Upwork",
        "requirement": "Build go-to-market strategy for new product. Identify customer segments, design pricing, create sales forecast, develop competitive positioning document.",
        "payment": 50000,
        "estimated_days": None,  # UNKNOWN
        "deadline": "Flexible",
        "application_url": "https://www.upwork.com/jobs/example8",
        "source_url": "https://www.upwork.com",
        "posted_date": "2024-10-04",
        "currency": "INR",
        "status": "NEW",
        "why_fit": "Excellent fit: business model, customer discovery, market analysis, commercial planning. Days unknown.",
    },
    {
        "project_client": "Trade Association India",
        "platform": "Freelancer",
        "requirement": "Forecast and analyze market trends for textile industry over next 5 years. Include competitor analysis, supply chain insights, pricing forecasts, growth projections.",
        "payment": 42000,
        "estimated_days": 9,
        "deadline": "15 days",
        "application_url": "https://www.freelancer.com/projects/example9",
        "source_url": "https://www.freelancer.com",
        "posted_date": "2024-10-01",
        "currency": "INR",
        "status": "NEW",
        "why_fit": "Great match: market research, forecasting, competitor analysis, market intelligence.",
    },
    {
        "project_client": "E-commerce Platform",
        "platform": "Workana",
        "requirement": "Customer discovery and segmentation study for new vertical. Interview 30+ potential customers, map buyer personas, assess willingness-to-pay, develop marketing angles.",
        "payment": 40000,
        "estimated_days": 12,
        "deadline": "20 days",
        "application_url": "https://www.workana.com/jobs/example10",
        "source_url": "https://www.workana.com",
        "posted_date": "2024-10-03",
        "currency": "INR",
        "status": "NEW",
        "why_fit": "Strong fit: customer discovery, market research, commercial strategy, opportunity analysis.",
    },
]
